---
- hosts: all,localhost
  become: true
  tasks:
    - name: Install docker
      apt:
        pkg:
          - docker.io
          - python3-pip
          - python3-docker
        state: latest
        update_cache: true

    - name: create dir
      ansible.builtin.file:
        path: ./helloworld
        state: directory
        mode: '0755'

    - name: git checkout
      ansible.builtin.git:
        repo: 'https://github.com/ssid334/d20b11b7-ef81-420f-8c81-8eaf5e3a19c4.git'
        dest: ./helloworld

    - name:
      docker_image:
        name: helloworld.image
        tag: 0.0.1
        build:
          path: ./helloworld
        source: build
        state: present

    - name: application container
      docker_container:
        name: helloworld
        image: helloworld.image:0.0.1
        state: present
        detach: yes
        pull: no
        ports:
          - "1433:443"
        command: sleep infinity
        restart_policy: always
        container_default_behavior: no_defaults
        detach: true
        command: python3 main.py

